apiVersion:  apps/v1
kind: Deployment
metadata:
  labels:
    app: automateforgood
  name: automateforgood
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: automateforgood
  template:
    metadata:
      labels:
        app: automateforgood

    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: automateforgood
        ports:
          - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}
        readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.containerPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}