apiVersion:  apps/v1
kind: Deployment
metadata:
  labels:
    app: automateforgood
  name: automateforgood
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automateforgood
  template:
    metadata:
      labels:
        app: automateforgood

    spec:
      containers:
      - image: arunprakashpj/automateforgood:latest
        imagePullPolicy: IfNotPresent
        name: automateforgood
        ports:
          - containerPort: 3111
            protocol: TCP
        livenessProbe:
          httpGet:
              path: /healthinfo
              port: 3111
        readinessProbe:
            httpGet:
              path: /healthinfo
              port: 3111
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"