apiVersion: v1
kind: Service
metadata: 
  labels:
    app: automateforgood
  name: automateforgood
  namespace: sandbox
spec:
  ports:
    - port: 4111
      targetPort: 3111
      protocol: TCP
  selector:
    app: automateforgood
  type: ClusterIP