apiVersion: v1
kind: Service
metadata: 
  labels:
    app: webapp
  name: webapp
  namespace: sandbox
spec:
  ports:
    - port: 4111
      targetPort: 3111
      protocol: TCP
  selector:
    app: webapp
  type: ClusterIP