namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

image:
  repository: arunprakashpj/automateforgood 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu:  250m
    memory: 64Mi
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111

livenessProbe:
  httpGet:
      path: /healthinfo
      port: 3111

readinessProbe:
  httpGet:
      path: /healthinfo
      port: 3111