name: AutomateForGood - Package with Docker
on: 
  push:
    branches:
      - 'main'
jobs: 
  docker-img-build-automateforgood:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        
        - name: "Install Chef Inspec"
          run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

        - name: "Run Infrastructure Tests"
          run: inspec exec test/my-profile --input-file test/my-profile/attributes.yml --reporter=cli html:./report.html --show-progress -t gcp://

        - uses: actions/upload-artifact@v2
          if: always()
          with:
            name: test-report
            path: ./report.html
          
        - uses: docker/login-action@v1
          with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
        - uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: arunprakashpj/automateforgood:latest, arunprakashpj/automateforgood:${{ github.sha }}

