name: AutomateForGood - Package with Docker
on: 
  push:
    branches:
      - 'main'
jobs: 
  docker-img-build-automateforgood:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        
        - name: "Install Chef Inspec"
          run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
          
        - uses: docker/login-action@v1
          with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
        - uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: arunprakashpj/automateforgood:latest, arunprakashpj/automateforgood:${{ github.sha }}

