name: Package with Docker
on: 
  push:
    branches:
      - 'main'
jobs: 
  test:
    name: Chef inSpec Test
    runs-on: ubuntu-18.04
    
      
    steps:
    - name: Install Chef Inspec
      run: |
        wget https://packages.chef.io/files/stable/inspec/4.20.2/ubuntu/18.04/inspec_4.20.2-1_amd64.deb
        sudo dpkg -i inspec_4.20.2-1_amd64.deb
        rm inspec_4.20.2-1_amd64.deb
        sudo inspec --chef-license=accept-silent
        
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Run Chef inSpec
      run: inspec exec spec
    
  docker-img-build-automateforgood:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: docker/login-action@v1
          with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
        - uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: arunprakashpj/automateforgood:latest, arunprakashpj/automateforgood:${{ github.sha }}
